import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-BR">
      <body>
        <header className="flex h-16 items-center justify-between border-b bg-background px-3 sm:px-6 sm:pl-2"></header>
        <main className="overflow-auto px-3 py-9 sm:px-6 min-w-full min-h-screen bg-background space-y-1 shadow-inner shadow-secondary-foreground/10">
          {children}
        </main>
      </body>
    </html>
  )
}
